### ISSUE TITLE
Suggest some new and awesome ideas

### ISSUE THREAD

**Issue by rockingrohit9639** [rockingrohit9639/TextAnalyzer#58]
## 💥 Proposal

* Suggest some new, awesome and unique ideas that we can implement in our project.
* You can also suggest some advanced ideas too, we can implement them together.
* You can also find bugs in our project and report them to me.

### Note
- If your idea is considered to be implemented in the project then only you will be given points.

**Comment by Akash20x** [comment]
We can implement an option to correct grammatical errors of the sentence input by user.

**Comment by rockingrohit9639** [comment]
> 5 ideas that can be implemented in this project:
> 
> 1. We can implement an option to correct grammatical errors of the sentence input by user.
> 2. We can also implement an option to display one random motivational quotes.
> 3. Sentiment Analysis for the text
> 4. Search if there is any link present in the text and return that link on result page.
> 5. If 1 word is present then check if it contain some meaning then return 3 examples related to that word.

Sounds good.
We will implement them.
Thank you @Akash20x

**Comment by kopinasaur** [comment]
Good day!

I think we should limit user to only one selection per operation here, otherwise some update is required to show results for all the selections. See screenshots below:

1) Four operations selected
![A](https://user-images.githubusercontent.com/79819309/109913826-a016b900-7ce9-11eb-8cee-846fe87e3226.JPG)


Turns out, only the first operation is executed:

2) Only "generate password" // "find word" is executed 
![B](https://user-images.githubusercontent.com/79819309/109913883-c0df0e80-7ce9-11eb-8e9c-9b572ec7fd95.JPG)


Cheers!

**Comment by rockingrohit9639** [comment]
> Good day!
> 
> I think we should limit user to only one selection per operation here, otherwise some update is required to show results for all the selections. See screenshots below:
> 
> 1. Four operations selected
>    ![A](https://user-images.githubusercontent.com/79819309/109913826-a016b900-7ce9-11eb-8cee-846fe87e3226.JPG)
> 
> Turns out, only the first operation is executed:
> 
> 1. Only "generate password" // "find word" is executed
>    ![B](https://user-images.githubusercontent.com/79819309/109913883-c0df0e80-7ce9-11eb-8e9c-9b572ec7fd95.JPG)
> 
> Cheers!

Thank you for this good suggestion. You can make an issue regarding it or I can create it.
